version: '3.9'
services:
  web:
    image: metikular/coupon-store
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://coupon_store:SECRET_PASSWORD@db/coupon_store
      - SECRET_KEY_BASE=change-me
      - HOST=coupons.example.com
    hostname: web
    restart: unless-stopped

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=coupon_store
      - POSTGRES_PASSWORD=SECRET_PASSWORD
    volumes:
      - coupon-store-database:/var/lib/postgresql/data

volumes:
  coupon-store-database:
