version: '3.9'
services:
  web:
    image: metikular/coupon-store
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    environment:
      - DATABASE_URL=sqlite3:db/data/coupons.sqlite3
      - SECRET_KEY_BASE=change-me
      - HOST=coupons.example.com
    hostname: web
    restart: unless-stopped
    volumes:
      - coupon-store-database:/app/db/data
      - coupon-store-storage:/app/storage

volumes:
  coupon-store-database:
  coupon-store-storage:
